name: Clippy Lint

on:
  pull_request:
    paths:
      - 'src-tauri/**'
      - '.github/workflows/lint-clippy.yml'
  workflow_dispatch:

env:
  HUSKY: 0
  CARGO_INCREMENTAL: 0

jobs:
  clippy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: windows-2022
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'v1-clippy'
          key: ${{ matrix.target }}
          workspaces: '. -> target'

      - name: Install Linux deps
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxslt1.1 libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Run Clippy
        working-directory: ./src-tauri
        run: cargo clippy --workspace --all-targets --target ${{ matrix.target }} -- -D warnings
