name: Check Formatting

on:
  pull_request:
    paths:
      - '**/*.rs'
      - '**/rustfmt.toml'
      - '.github/workflows/rustfmt.yml'
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --manifest-path ./src-tauri/Cargo.toml --all -- --check
